### ISSUE TITLE
Fail to build on Windows using VS Code

### ISSUE THREAD

**Issue by breadli428** [cmm-21/a0#3]
![2](https://user-images.githubusercontent.com/57526478/110012602-fd7a2c80-7d20-11eb-9305-e7faf958fd84.jpg)

![SharedScreenshot](https://user-images.githubusercontent.com/57526478/110012548-ec312000-7d20-11eb-9be1-ee574506b3a4.jpg)

Hi,

I switched to using the complier of Visual Studio in VS Code, however it still fails to build. Could someone please help?

Thanks in advance!

Chenhao

**Comment by eastskykang** [comment]
It seems somehow your cmake cannot find your build directory. Can you give me more details? What is the path of the source code?

**Comment by breadli428** [comment]
![1](https://user-images.githubusercontent.com/57526478/110031710-8b611200-7d37-11eb-81db-a81e0e4354d0.png)
By "path of the source code" I guess you mean where I put the whole folder? It's the one highlighted above.

For your reference you can also see the path below.

![image](https://user-images.githubusercontent.com/57526478/110031908-ca8f6300-7d37-11eb-939c-871066ed53ee.png)

With the failure reported.

**Comment by breadli428** [comment]
No there is not CMakeLists in the mentioned path.

![image](https://user-images.githubusercontent.com/57526478/110032087-0aeee100-7d38-11eb-9622-4d92b716f75e.png)

**Comment by breadli428** [comment]
I clone the repo from github in VS Code, as taught in today's tutorial. And then it started to build itself, and then it failed but still created the build folder. I guess the build folder is not intact because of the failure?

**Comment by eastskykang** [comment]
how about eigen-build and eigen-src directory? is it also empty?

**Comment by eastskykang** [comment]
@breadli428 VS Code tries to "configure" your source code which mean it automatically runs 
```
$ cmake
``` 

as you open the folder, which generate ```build``` directory.

**Comment by breadli428** [comment]
Yes they are all empty, as you can see in the last picture, almost all folders under deps_ are empty. I believe this is because the build did not succeed.

**Comment by eastskykang** [comment]
This is pretty odd... it should download all the dependency code by cmake and somehow it does not. May I ask your cmake version?

**Comment by breadli428** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/57526478/110033223-679ecb80-7d39-11eb-933e-8321bbd3b448.jpg)

It is the latest one (cmake version 3.20.0-rc3), I just downloaded it.

**Comment by eastskykang** [comment]
Okay let's have a quick zoom call if it's fine for you. I will send you a DM

**Comment by breadli428** [comment]
![SharedScreenshot](https://user-images.githubusercontent.com/57526478/110033375-974dd380-7d39-11eb-9992-e3634a7018cc.jpg)

And this is the one I downloaded and installed.

**Comment by breadli428** [comment]
Cool of course! Thanks for the patience!

**Comment by eastskykang** [comment]
In the latest CMake version, fetch_content behavior was changed to download dependency code to another location. 

So please downgrade your cmake version if you have similar problem. I will later update README.md.

**Comment by moritzge** [comment]
For this assignment, I suggest you install the "Latest Release (3.19.6.)" instead of the "Release Candidate (3.20.0-rc3)" from https://cmake.org/download/. You have to scroll down to find 3.19.6.

We will make future assignments compatible with 3.20.0-rc3.

If you install cmake with a package manager (e.g. brew, apt install, ... ) most likely it will install a cmake version < 3.20.

I am closing this issue now. If you still have issues, let us know :)
