### ISSUE TITLE
Compile did not succeed because source directory didn't find CMakeLists.txt file 

### ISSUE THREAD

**Issue by madBot42** [cmm-21/a0#5]
Hello :)

I was able to clone the repository etc. successfully but I am not able to build the project. It appears that it's not able to find CMakeLists.txt files (see pictures).

I used "Visual Studio Community 2019" for Windows and downloaded/added all the necessary tools you've listed.

![image_2021-03-05_154827](https://user-images.githubusercontent.com/26327636/110131225-391d0100-7dca-11eb-9cb4-45a71072adda.png)

![image_2021-03-05_154857](https://user-images.githubusercontent.com/26327636/110131299-4afea400-7dca-11eb-9360-c8596ad1ccb9.png)

What could be the problem?

Have a nice evening
Madeleine

**Comment by liyuesolo** [comment]
Fixed by downgrading cmake to 3.18
