### ISSUE TITLE
git classroom Test fails on cmake File error

### ISSUE THREAD

**Issue by robindurkowitzer** [cmm-21/a0#6]
I am still having some minor troubles with git.
When I use the commit an push functions in my VS Code environment it did not push the code to the repository.
When I did it using the git bash commandline it worked, but the test fails on a strange error:

CMake Error: The current CMakeCache.txt directory /home/runner/work/a0-robindurkowitzer/a0-robindurkowitzer/CMakeCache.txt is different than the directory c:/Users/Robin/Documents/ETH/FS_21/CMM/a0-robindurkowitzer where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt

I am not sure where I should change that file or if it was just generated wrong. 

Edit: The test in VS Code passes, it is just the Test on GitHub that fails.

**Comment by moritzge** [comment]
Hi Robin,

You shouldn't commit CMakeCache.txt.
I deleted it from your repo, see commit: https://github.com/cmm-21/a0-robindurkowitzer/commit/16c8145ca4a49e39afac5a6fa3200a4d1e72833a

Moritz

**Comment by robindurkowitzer** [comment]
Great thanks!
