### ISSUE TITLE
Necessity of the Visual Studio Community Release 2019 kit for assignments

### ISSUE THREAD

**Issue by hugorilla** [cmm-21/a0#7]
Hi! Just a quick question. I managed to get the code for this assignment working on my Windows machine using Visual Studio Code and the GCC compiler I already had installed on my system (i.e. my active kit is GCC 6.3.0). Is this okay? Do future assignments rely on having Visual Studio Community Release 2019 as the active kit?

**Comment by eastskykang** [comment]
Hi Hugo, 

You can use any compiler you prefer as far as it supports C++17 standard. FYI, I'm using GCC 8 or GCC 9 and apple clang 12. 
But from my experience, Visual Studio Code has better integration with MSVC.

Hope this helps!

**Comment by hugorilla** [comment]
Great! Thanks for your help.
